# Copyright 2025 Lewa-Reka <lewareka.yt@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  name: deye-inverter
  friendly_name: "Deye Inverter"
  device_description: "Deye Inverter SG0XLP3"
  modbus_controller_id: deye_modbus_controller
  baud_rate: "9600"
  inverter_prefix: "inv3p"
  inverter_name: "Deye 3P"
  # Safe Mode Default parameters
  default_maximum_battery_charge_current: "140" # Amps
  default_max_sell_power: "12000" # Watts
  default_system_work_mode: "Zero Export To Load" # "Selling First", "Zero Export To Load", "Zero Export To CT"
  default_solar_sell: "on" # "on", "off"
  default_force_off_grid: "off" # "on", "off"

packages:
  init: !include packages/init.yaml
  battery: !include packages/deye_hybrid_3p/battery_3p.yaml
  gen: !include packages/deye_hybrid_3p/gen_3p.yaml
  grid: !include packages/deye_hybrid_3p/grid_3p.yaml
  load: !include packages/deye_hybrid_3p/load_3p.yaml
  work_mode: !include packages/deye_hybrid_3p/work_mode_3p.yaml
  device: !include packages/deye_hybrid_3p/device_3p.yaml
  inverter: !include packages/deye_hybrid_3p/inverter_3p.yaml
  pv: !include packages/deye_hybrid_3p/pv_3p.yaml
  tou: !include packages/deye_hybrid_3p/tou_3p.yaml
  time_sync: !include packages/deye_hybrid_3p/time_sync_3p.yaml

script:
  - id: ${inverter_prefix}_set_safe_modbus_registers
    then:
      - logger.log:
          level: INFO
          format: "Setting safe Modbus register values"
      - number.set:
          id: ${inverter_prefix}_maximum_battery_charge_current
          value: ${default_maximum_battery_charge_current}
      - number.set:
          id: ${inverter_prefix}_max_sell_power
          value: ${default_max_sell_power}
      - select.set:
          id: ${inverter_prefix}_system_work_mode
          option: ${default_system_work_mode}
      - switch.turn_${default_solar_sell}:
          id: ${inverter_prefix}_switch_solar_sell
      - switch.turn_${default_force_off_grid}:
          id: ${inverter_prefix}_switch_off_grid
