substitutions:
  name: deye-inverter
  friendly_name: "Deye Inverter"
  device_description: "Deye Inverter SG0XLP1"
  modbus_controller_id: deye_modbus_controller
  baud_rate: "9600"
  inverter_prefix: "inv1p"
  inverter_name: "Deye 1P"
  # Safe Mode Default parameters
  default_maximum_battery_charge_current: "130" # Amps
  default_max_sell_power: "6000" # Watts
  default_system_work_mode: "Zero Export To Load" # "Selling First", "Zero Export To Load", "Zero Export To CT"
  default_solar_sell: "on" # "on", "off"

packages:
  init: !include packages/init.yaml
  battery: !include packages/deye_hybrid_1p/battery_1p.yaml
  gen: !include packages/deye_hybrid_1p/gen_1p.yaml
  grid: !include packages/deye_hybrid_1p/grid_1p.yaml
  load: !include packages/deye_hybrid_1p/load_1p.yaml
  work_mode: !include packages/deye_hybrid_1p/work_mode_1p.yaml
  device: !include packages/deye_hybrid_1p/device_1p.yaml
  inverter: !include packages/deye_hybrid_1p/inverter_1p.yaml
  pv: !include packages/deye_hybrid_1p/pv_1p.yaml
  tou: !include packages/deye_hybrid_1p/tou_1p.yaml

script:
  - id: ${inverter_prefix}_set_safe_modbus_registers
    then:
      - logger.log:
          level: INFO
          format: "Setting safe Modbus register values"
      - number.set:
          id: ${inverter_prefix}_maximum_battery_charge_current
          value: ${default_maximum_battery_charge_current}
      - number.set:
          id: ${inverter_prefix}_max_sell_power
          value: ${default_max_sell_power}
      - select.set:
          id: ${inverter_prefix}_system_work_mode
          option: ${default_system_work_mode}
      - switch.turn_${default_solar_sell}:
          id: ${inverter_prefix}_switch_solar_sell
